### ISSUE TITLE
Atlas + border cause textures to be drawn incorrectly

### ISSUE THREAD

**Issue by CyberYoshi64** [devkitPro/tex3ds#32]
This issue is a continuation from [this issue](https://github.com/devkitPro/tex3ds/issues/12)

Besides not really tiling the textures well, causes certain textures to be rotated incorrectly upon either using `C2D_DrawImage` or drawing as a C2D sprite.
It also looks like the offsets in the atlas are not applied correctly, as of one of the corners gets cut off and the scaling is also incorrect. The graphics should be pixel-perfect in these 2 screenshots
![badrotation](https://user-images.githubusercontent.com/35138367/141163323-d1e21448-3c0c-415c-885b-513fd8aead1e.png)

If I remove the `--border` option, the graphics appear properly:
![goodsprites](https://user-images.githubusercontent.com/35138367/141163963-058f7675-059a-4e1f-84b6-0812b03891f8.png)
however, this button (and the seperate textures linked to it) animate with scaling and rotation, which would bleed into another texture on the same sheet.

If you need to see how tex3DS made the sheets:

With `--border`
![atlas_with_border](https://user-images.githubusercontent.com/35138367/141165171-69e6bd44-0f7e-4432-a24c-9f3df53dd288.png)

... and without
![atlas_wo_border](https://user-images.githubusercontent.com/35138367/141165176-90f5f9e9-22c4-473e-a89d-5c4e4a49dd58.png)

(Yes, I am aware that the sheet sizes are limited to 2^n exclusively, so that button graphic is too big to be squeezed in and I could split it but this doesn't change the point and the issue still occurs)

**Comment by piepie62** [comment]
At least part of this (the scaling/corner cutoff) should have been solved by #30. As for the rotation part, I'll see if I can figure out what's going on there.

**Comment by CyberYoshi64** [comment]
I did make sure to update devkitPro and recompile my project but looks like it seems to only be partially fixed.
(cannot tell, haven't bothered scaling/rotating textures until now)

**Comment by mtheall** [comment]
Are you able to build tex3ds yourself? If so, can you try out the [border-fix](https://github.com/devkitPro/tex3ds/tree/border-fix) branch?

**Comment by CyberYoshi64** [comment]
> Are you able to build tex3ds yourself? If so, can you try out the border-fix branch?

It's a bit confusing to build but I can and I did.
Although if a texture width + border is just as big as the sheet height, still has a pixel row cut off, but otherwise it worked.

**Comment by mtheall** [comment]
I pushed up some more code to the same branch. Can you try that one out and report back?

**Comment by CyberYoshi64** [comment]
Yes, now it works. Thank you.
(BTW couldn't respond earlier due to someone having disabled commenting for randoms in this repo)
